config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope :legacy do
    resources :datasets, only: %i(index show), controller: 'legacy_datasets', as: 'legacy_datasets'
  end

  resources :datasets, only: %i(index show create)
  resources :authentications, only: %i(index create) do
    post 'login', on: :collection
    delete 'logout', on: :collection
  end  
  root to: 'authentications#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/jobs', constraints: LoggedInConstraint.new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hplc_dataset.rb
require 'hplc'
require 'zip'

class HplcDataset < ApplicationRecord

  def zip_file
    io = StringIO.new
    io << Base64.decode64(encoded_zip)
    io.rewind
    Zip::File.open_buffer(io)
  end

  def process!
    parser = HPLCParser.new
    kb = KnowledgeBase.new
    generator = OutputGenerator.new
    zf = zip_file
    zf.entries.each do |entry|
      next if entry.name[0...2] == "__"
      io = zf.get_input_stream(entry)
      datapoints = parser.parse(io, filename: entry.name)
      kb.resolve(datapoints)
      datapoints.each { |dp| generator.add(dp) }
    end

    update_attributes(processed_data: generator.to_csv)
  end

  def self.from_zip(filename, io)
    new(filename: filename, encoded_zip: Base64.encode64(io.read))
  end
end

app/models/processing_request.rb
class ProcessingRequest < ApplicationRecord
  INPUT_FOLDER = Rails.root.join('public/processing_requests/input')
  OUTPUT_FOLDER = Rails.root.join('public/processing_requests/output')
  belongs_to :user
  validate :validates_input_and_output_file_paths, on: :save
  before_destroy { |record|
    File.delete(original_file_path) if original_file_path.present? && File.exists?(original_file_path)
    File.delete(processed_file_path) if processed_file_path.present? && File.exists?(processed_file_path)
  }

  def write_input_file_to_disk!(tempfile)
    tempfile.rewind
    self.original_file_path = File.join(INPUT_FOLDER, "#{self.id}.zip")
    File.open(original_file_path, "wb") do |f|
      f << tempfile.read
      f.flush
    end
    save!
  end

  def prepare_output_file!
    self.processed_file_path ||= File.join(OUTPUT_FOLDER, "#{self.id}.csv")
    # Clear out file contents
    File.open(processed_file_path, "wb") { |f| f.flush }
    save!
  end

  def output_file_handle(&blk)
    File.open(processed_file_path, "ab") do |f|
      yield(f)
    end
  end

  def write_output_to_disk(results)
    self.processed_file_path = File.join(OUTPUT_FOLDER, "#{self.id}.csv")
    File.open(processed_file_path, "wb") do |f|
      f << results
      f.flush
    end
    save!
  end

  def processed?
    processed_file_path.present? && File.exists?(processed_file_path) && percentage_processed >= 1
  end

  private
  def validates_input_and_output_file_paths
    if original_file_path.present? && !original_file_path.start_with?(INPUT_FOLDER)
      errors.add(:original_file_path, "path is not valid")
    end

    if processed_file_path.present? && !processed_file_path.start_with(OUTPUT_FOLDER)
      errors.add(:processed_file_path, "path is not valid")
    end
  end
end

app/models/skinny_hplc_dataset.rb
class SkinnyHplcDataset
  SKINNY_HPLC_QUERY = <<-QUERY
    select
      id, filename,
      length(encoded_zip) as original_file_size,
      length(processed_data) as processed_file_size
    from 
      hplc_datasets
  QUERY

  def self.records
    records = ActiveRecord::Base.connection.execute(SKINNY_HPLC_QUERY).values
    records.map do |(id, filename, original_bytes, processed_bytes)|
      SkinnyHplcDataset.new(id, filename, original_bytes, processed_bytes)
    end
  end

  attr_reader :id, :filename, :original_file_size, :processed_file_size
  def initialize(id, filename, original_file_size, processed_file_size)
    @id = id
    @filename = filename
    @original_file_size = original_file_size
    @processed_file_size = processed_file_size
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_attributes
  validates :email, :username, presence: true
  has_secure_password
  has_many :processing_requests

  private
  def downcase_attributes
    self.username = username.downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :user_logged_in?
  
  protected

  def user_logged_in?
    session[:user_id].present? && current_user.present?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def invalid_authentication_error
    flash[:notice] = "Invalid Credentials"
    redirect_to root_path
  end

  def current_user
    @current_user ||= User.where(id: session[:user_id]).first
  end
end

app/controllers/authenticated_accounts_controller.rb
class AuthenticatedAccountsController < ApplicationController
  before_action :ensure_user_logged_in

  private
  def ensure_user_logged_in
    redirect_to root_path unless user_logged_in?
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  helper_method :user
  before_action :redirect_if_logged_in, except: :logout
  def index
  end

  def create
    user = User.where(username: create_params[:username], email: create_params[:email]).first_or_initialize
    invalid_authentication_error and return unless user.id.blank?
    user.update_attributes(create_params)
    if user.save
      log_in(user)
      redirect_to datasets_path and return
    end
    redirect_to root_path
  end

  def login
    user = User.where(username: login_params[:username]).first
    invalid_authentication_error and return unless user && user.authenticate(login_params[:password])
    log_in(user)
    redirect_to datasets_path
  end

  def logout
    reset_session if user_logged_in?
    flash[:notice] = "Logged Out"
    redirect_to root_path
  end

  private
  def user
    @user ||= User.new
  end

  def redirect_if_logged_in
    redirect_to datasets_path if user_logged_in?
  end

  def login_params
    @login_params ||= params.require(:user).permit(:username, :password)
  end

  def create_params
    @create_params ||= params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/datasets_controller.rb
class DatasetsController < AuthenticatedAccountsController
  helper_method :processing_requests
  before_action :verify_file_type, only: %i(create)
  def index
  end

  def show
    csv = File.read processing_request.processed_file_path
    send_data csv, filename: "#{processing_request.name}.processed.csv"
  end

  def create
    zip = processing_request_params[:zipfile]
    processing_request = current_user.processing_requests.create(name: processing_request_params[:name])
    begin
      processing_request.write_input_file_to_disk!(zip.tempfile)
      HplcPreprocessingJob.perform_later(id: processing_request.id)
    rescue => exception
      processing_request.destroy!
      flash[:error] = "The processing request could not be uploaded to the server"
      raise exception
    end
    redirect_to datasets_path
  end

  private
  def processing_requests
    @processing_requests ||= current_user.processing_requests
  end

  def processing_request
    @processing_request ||= current_user.processing_requests.find(params[:id])
  end

  def processing_request_params
    params.require(:processing_request).permit(:name, :zipfile)
  end

  def verify_file_type
    extension = File.extname(processing_request_params[:zipfile].original_filename)
    return if extension == ".zip"
    flash[:error] = "Job requests must be submitted as compressed ZIP files"
    redirect_to datasets_path
  end
end

app/controllers/legacy_datasets_controller.rb
class LegacyDatasetsController < AuthenticatedAccountsController
  def index
    @datasets = SkinnyHplcDataset.records
    @dataset = HplcDataset.new
  end

  def show
    dataset = HplcDataset.find(params[:id])
    send_data(dataset.processed_data, :type => 'text/csv; charset=utf-8; header=present', :filename => dataset.filename.gsub('.zip', '.csv'))
  end

  def create
    zip = dataset_params[:zipfile]
    dataset = HplcDataset.from_zip(zip.original_filename, zip.tempfile)
    dataset.save!
    dataset.process!
    redirect_to datasets_path
  end

  private
  def dataset_params
    params.require(:hplc_dataset).permit(:zipfile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentications/index.html.erb
<div class="row">
  <h2>Existing User Login</h2>
  <%= form_for user, url: login_authentications_path do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit 'Log In' %>
  <% end %>
</div>

<div class="row">
  <h2>New User Signup</h2>
  <%= form_for user, url: authentications_path do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit 'Create Account' %>
    
  <% end %>
</div>

app/views/datasets/index.html.erb
<h1>Upload a new Dataset</h1>
<%= form_for ProcessingRequest.new, url: datasets_path, method: :post do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :zipfile %>
  <%= f.file_field :zipfile %>
  <%= f.submit "Upload for processing" %>
<% end %>

<h1>Prior Processing Submissions</h1>
<ul>
  <% processing_requests.each do |pr| %>
    <li>
      <%= pr.name %>
      <% if pr.processed? %>
        <%= link_to "Download CSV", dataset_path(pr) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaneHplcWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notice">
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>
    <% if user_logged_in? %>
      <div class="user-controls">
        <%= link_to('Logout', logout_authentications_path, method: :delete) %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/legacy_datasets/index.html.erb
<ul>
  <% @datasets.each do |dataset| %>
    <li>
      <%= dataset.filename %>
      <% if dataset.processed_file_size.present? %>
        <%= link_to "Download CSV", dataset_path(dataset.id), target: '_blank' %>
      <% end %>
    </li>
  <% end %>
</ul>